backend:
  name: git-gateway
  branch: master
local_backend: true
media_folder: "public/assets/img/uploads"
public_folder: "/assets/img/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"} 
      - {label: "Date", name: "datePost", widget: "datetime"} 
      - {label: "Tags", name: "tag", widget: "list"} 
      - {label: "Abstract", name: "abstract", widget: "markdown", minimal: true} 
      - {label: "Body", name: "body", widget: "markdown"} 